### ISSUE TITLE
Error during planning: Invalid function `current_setting`

### ISSUE THREAD

**Issue by greyscaled** [GlareDB/glaredb#1060]
## Context

I'm trying to run [`pg_activity`](https://github.com/dalibo/pg_activity) against my `glaredb` instance.

## Expected

I can connect and it works

## Actual

I can't connect, because `pg_activity` is calling a postgres system function that glaredb has not yet implemented, `current_setting`

```
Traceback (most recent call last):
  File "/usr/bin/pg_activity", line 33, in <module>
    sys.exit(load_entry_point('pg-activity==2.2.1', 'console_scripts', 'pg_activity')())
  File "/usr/lib/python3/dist-packages/pgactivity/cli.py", line 263, in main
    dataobj = data.pg_connect(
  File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 337, in pg_connect
    data = Data.pg_connect(
  File "/usr/lib/python3/dist-packages/pgactivity/data.py", line 103, in pg_connect
    cur.execute(queries.get("is_superuser"))
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.InternalError_: Error during planning: Invalid function 'current_setting'
```

According to the [postgres docs for `current_setting`](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET)

> current_setting ( setting_name text [, missing_ok boolean ] ) → text
> 
> Returns the current value of the setting setting_name. If there is no such setting, current_setting throws an error unless missing_ok is supplied and is true (in which case NULL is returned). This function corresponds to the SQL command [SHOW](https://www.postgresql.org/docs/current/sql-show.html).

current_setting('datestyle') → ISO, MDY

## Impact

postgres compat

**Comment by greyscaled** [comment]
This function is used to check a bunch of values:

https://github.com/search?q=repo%3Adalibo%2Fpg_activity%20current_setting&type=code
