### ISSUE TITLE
Type assertion failure with polars (LargeUtf8 vs Utf8)

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1339]
## Context

Using the following python script:

```python
import glaredb
import polars as pl
import time

con = glaredb.connect()

def time_run(func):
    start_time = time.monotonic()
    func()
    return time.monotonic() - start_time

con.execute("""
CREATE EXTERNAL DATABASE demo_pg
    FROM postgres
    OPTIONS (
        host = 'pg.demo.glaredb.com',
        port = '5432',
        user = 'demo',
        password = 'demo',
        database = 'postgres',
    );
""")

lineitem_pg = con.sql("select * from demo_pg.public.lineitem limit 5").to_polars()
lineitem_parquet = con.sql("select * from parquet_scan('https://storage.googleapis.com/glaredb-benchmarks/data/tpch/sf1/lineitem/part-0.parquet') limit 5").to_polars()

def q1_pg():
    df = con.sql("""
    select
        l_returnflag,
        l_linestatus,
        sum(l_quantity) as sum_qty,
        sum(l_extendedprice) as sum_base_price,
        sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
        sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
        avg(l_quantity) as avg_qty,
        avg(l_extendedprice) as avg_price,
        avg(l_discount) as avg_disc,
        count(*) as count_order
    from
        lineitem_pg
    where
        l_shipdate <= '1998-09-02'
    group by
        l_returnflag,
        l_linestatus
    order by
        l_returnflag,
        l_linestatus
    """).to_polars()
    print(df)

def q1_parquet():
    df = con.sql("""
    select
        l_returnflag,
        l_linestatus,
        sum(l_quantity) as sum_qty,
        sum(l_extendedprice) as sum_base_price,
        sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
        sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge,
        avg(l_quantity) as avg_qty,
        avg(l_extendedprice) as avg_price,
        avg(l_discount) as avg_disc,
        count(*) as count_order
    from
        lineitem_parquet
    where
        l_shipdate <= '1998-09-02'
    group by
        l_returnflag,
        l_linestatus
    order by
        l_returnflag,
        l_linestatus
    """).to_polars()
    print(df)

pg_time = time_run(q1_pg)
print(f"df from pg: {pg_time}")

parquet_time = time_run(q1_parquet)
print(f"df from parquet: {parquet_time}")
```

I get this error:

```
thread 'glaredb-python-thread-3' panicked at 'assertion failed: `(left == right)`
  left: `LargeUtf8`,
 right: `Utf8`: StringArray expects DataType::Utf8', /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-42.0.0/src/array/byte_array.rsthread 'thread ':glaredb-python-thread-1' panicked at 'assertion failed: `(left == right)`
  left: `LargeUtf8`,
 right: `Utf8`: StringArray expects DataType::Utf8glaredb-python-thread-2', ' panicked at '/Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-42.0.0/src/array/byte_array.rsassertion failed: `(left == right)`
  left: `LargeUtf8`,
 right: `Utf8`: StringArray expects DataType::Utf8454', :/Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-array-42.0.0/src/array/byte_array.rs9
:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
454:9
:454:9
Traceback (most recent call last):
  File "/Users/sean/Code/github.com/glaredb/glaredb/py-glaredb/examples/test.py", line 79, in <module>
    pg_time = time_run(q1_pg)
  File "/Users/sean/Code/github.com/glaredb/glaredb/py-glaredb/examples/test.py", line 9, in time_run
    func()
  File "/Users/sean/Code/github.com/glaredb/glaredb/py-glaredb/examples/test.py", line 50, in q1_pg
    """).to_polars()
pyo3_runtime.PanicException: assertion failed: `(left == right)`
  left: `LargeUtf8`,
 right: `Utf8`: StringArray expects DataType::Utf8
```

## Expected

No error

## Actual

Error

**Comment by universalmind303** [comment]
this is actually a very common issue with polars. They only use arrow's `LargeUtf8`, so any conversion to/from polars strings usually requires either the use of `LargeUtf8`, or conversion to `Utf8`.
