### ISSUE TITLE
RPC: Panic - 'function should have a specified runtime at this point. This is a bug.'

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#1689]
## Description

I just tried running the postgres SLTs with RPC and got the following panic. Still working on _which_ query it failed on.

```
Info: panicked at 'function should have a specified runtime at this point. This is a bug.', crates/sqlexec/src/planner/context_builder.rs:342:55

Backtrace:   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/backtrace.rs:332:13
   3: testing::slt::cli::Cli::run::{{closure}}
             at ./src/slt/cli.rs:103:29
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
   5: std::panicking::rust_panic_with_hook
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:709:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:595:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
   8: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   9: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  10: sqlexec::planner::context_builder::PartialContextProvider::handle_function_dispatch::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/planner/context_builder.rs:342:55
  11: sqlexec::planner::context_builder::PartialContextProvider::resolve_reference::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/planner/context_builder.rs:235:70
  12: <sqlexec::planner::context_builder::PartialContextProvider as datafusion_ext::planner::AsyncContextProvider>::get_table_func::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/planner/context_builder.rs:416:14
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
  14: datafusion_ext::planner::relation::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::create_relation::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/relation/mod.rs:66:30
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
  16: datafusion_ext::planner::relation::join::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::plan_table_with_joins::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/relation/join.rs:37:70
  17: datafusion_ext::planner::select::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::plan_from_tables::{{closure}}
j          at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/select.rs:283:67
  18: datafusion_ext::planner::select::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::select_to_plan::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/select.rs:69:72
  19: datafusion_ext::planner::set_expr::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::set_expr_to_plan::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/set_expr.rs:33:76
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
  21: datafusion_ext::planner::query::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::query_to_plan_with_schema::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/query.rs:85:70
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
  23: datafusion_ext::planner::query::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::query_to_plan_with_context::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/query.rs:42:64
  24: datafusion_ext::planner::query::<impl datafusion_ext::planner::SqlQueryPlanner<S>>::query_to_plan::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/datafusion_ext/src/planner/query.rs:34:14
  25: sqlexec::planner::session_planner::SessionPlanner::plan_statement::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/planner/session_planner.rs:610:54
  26: sqlexec::planner::session_planner::SessionPlanner::plan_ast::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/planner/session_planner.rs:85:83
  27: sqlexec::context::local::PreparedStatement::build::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/context/local.rs:408:56
  28: sqlexec::context::local::LocalSessionContext::prepare_statement::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/context/local.rs:238:57
  29: sqlexec::session::Session::prepare_statement::{{closure}}
             at /Users/sean/Code/github.com/glaredb/glaredb/crates/sqlexec/src/session.rs:459:56
  30: <testing::slt::test::TestClient as sqllogictest::runner::AsyncDB>::run::{{closure}}
             at ./src/slt/test.rs:299:26
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
  32: sqllogictest::runner::Runner<D,M>::apply_record::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqllogictest-0.15.2/src/runner.rs:604:62
  33: sqllogictest::runner::Runner<D,M>::run_async::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqllogictest-0.15.2/src/runner.rs:679:58
  34: sqllogictest::runner::Runner<D,M>::run_multi_async::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqllogictest-0.15.2/src/runner.rs:864:36
  35: testing::slt::test::Test::execute::{{closure}}
             at ./src/slt/test.rs:107:22
  36: testing::slt::cli::Cli::run_test::{{closure}}::run_test_inner::{{closure}}
             at ./src/slt/cli.rs:390:18
  37: testing::slt::cli::Cli::run_test::{{closure}}
             at ./src/slt/cli.rs:405:89
  38: testing::slt::cli::Cli::run_tests::{{closure}}::{{closure}}
             at ./src/slt/cli.rs:296:92
  39: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
  40: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:311:17
  41: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/loom/std/unsafe_cell.rs:14:9
  42: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:300:13
  43: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:476:19
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  45: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  46: ___rust_try
  47: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  48: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  49: tokio::runtime::task::harness::poll_future
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:464:18
  50: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:198:27
  51: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:152:15
  52: tokio::runtime::task::raw::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:276:5
  53: tokio::runtime::task::raw::RawTask::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:200:18
  54: tokio::runtime::task::LocalNotified<S>::run
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/mod.rs:400:9
  55: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:639:17
  56: tokio::runtime::coop::with_budget
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  57: tokio::runtime::coop::budget
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  58: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:575:9
  59: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:526:24
  60: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:491:21
  61: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9
  62: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:26
  63: std::thread::local::LocalKey<T>::try_with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/local.rs:270:16
  64: std::thread::local::LocalKey<T>::with
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/local.rs:246:9
  65: tokio::runtime::context::set_scheduler
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:9
  66: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:486:9
  67: tokio::runtime::context::runtime::enter_runtime
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  68: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:478:5
  69: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/worker.rs:447:45
  70: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/task.rs:42:21
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:311:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/core.rs:300:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:476:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  77: ___rust_try
  78: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  79: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  80: tokio::runtime::task::harness::poll_future
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:464:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:198:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/harness.rs:152:15
  83: tokio::runtime::task::raw::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:276:5
  84: tokio::runtime::task::raw::RawTask::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/raw.rs:200:18
  85: tokio::runtime::task::UnownedTask<S>::run
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/task/mod.rs:437:9
  86: tokio::runtime::blocking::pool::Task::run
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:159:9
  87: tokio::runtime::blocking::pool::Inner::run
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:513:17
  88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/blocking/pool.rs:471:13
  89: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:135:18
  90: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/mod.rs:529:17
  91: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  92: std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  93: ___rust_try
  94: std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  95: std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  96: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/mod.rs:528:30
  97: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  98: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  99: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
 100: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17
 101: __pthread_joiner_wake

```

**Comment by scsmithr** [comment]
Fails on this query:

```
query T
SELECT * FROM list_schemas(external_db) WHERE schema_name = 'public';
----
public
```

https://github.com/glaredb/glaredb/blob/61624241b05f960a866ed902d34c300736d95800/testdata/sqllogictests_postgres/external_database.slt#L39-L42

**Comment by universalmind303** [comment]
i'll take a look at this one.

**Comment by universalmind303** [comment]
I think this is the same as the `generate_series`. They need to inherit the runtime from the parent.
