### ISSUE TITLE
Can't connect to GlareDB with Npgsql

### ISSUE THREAD

**Issue by Seddryck** [GlareDB/glaredb#2039]
I tried to connect from a simple .NET solution with the help of [Npgsql](https://github.com/npgsql/npgsql), the most commonly used .NET data provider for PostgreSQL. I already used this package to connect to non postgresql servers such as CockRoach, QuestDB, Timescale.

When trying to connect to a cloud instance of GlareDB, I'm using the following connection-string:

```
"Host=***.remote.glaredb.com;Port=6443;Username=****;Password=****;Database=hidden_cherry"
```
and receiving the following exception:
```
Received unknown response \0 for SSLRequest (expecting S or N)
```
I tried to add the option `sslmode=disable` but then receiving another error message:
```
Unknown message code: 0
   at Npgsql.Util.PGUtil.ValidateBackendMessageCode(BackendMessageCode code)
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.Internal.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|216_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.PoolingDataSource.<Get>g__RentAsync|28_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.Open()
...
```

If you need additional information feel free to ask.

**Comment by greyscaled** [comment]
The host and port in the string are incorrect for connecting with Npgsql. You'll want `proxy.glaredb.com` and `6543`.

`remote.glaredb.com` and `6443` are for RPC only, which is supported in our CLI and Python bindings.

```
"Host=***.proxy.glaredb.com;Port=6543;Username=****;Password=****;Database=hidden_cherry"
```

That said, we do have a bug (even with the correct host/port) (https://github.com/GlareDB/glaredb/issues?q=is%3Aissue+is%3Aopen+pg_type) that affects postgres-compatibility with a few tools and vendors. If we implement `pg_type` properly we should be able to resolve this.

**Comment by greyscaled** [comment]
Just an update here, I did actually manage to get this running with Npgsql `8.0.0-rc.2` (I'm running `dotnet` 7.0 in Ubuntu).

If you make the changes to host/port, and perhaps update Npgsql, are you able to get it running?

**Comment by Seddryck** [comment]
Reading your initial comments about pg_type, I added to the connection string the option `Server Compatibility Mode=NoTypeLoading` (and naturally adapt, based on your suggestions, the host and the port). It was working (using Npgsql 7.0.6).

If I don't add the option `Server Compatibility Mode`, it's also working.

Issue solved.

**Comment by greyscaled** [comment]
Thanks for the update @Seddryck . I think there's more for us to do here on the web UI since we aren't making it clear enough which connection string to copy/paste.

Maybe it would be nice to have a selector for various languages!

**Comment by Seddryck** [comment]
I don't know if you prefer that I'm adding a issue or anything else, but I found a potential issue with Npgsql and GlareDB.

As explained [here](https://github.com/npgsql/npgsql/issues/2920), Npgsql is creating the statement `DISCARD ALL` at the close of each SQL connection (which is light in Npgsql). Unfortunately, this statement is not supported by GlareDB. You can workaround this by adding `No Reset On Close=true` to your connection string

**Comment by scsmithr** [comment]
Thanks for bringing that up, I opened up an issue for the `DISCARD ...` statements here: https://github.com/GlareDB/glaredb/issues/2059

**Comment by 64J0** [comment]
Were you able to use Npgsql to create the tables at GlareDB? I'm constantly getting this mysterious error when I try to use that command:

```sql
CREATE EXTERNAL TABLE @p1
FROM s3
OPTIONS (
    access_key_id = '@p2',
    secret_access_key = '@p3',
    region = '@p4',
    bucket = '@p5',
    location = '@p6'
); 
```

Error message:

```bash
Exception data: System.AggregateException: One or more errors occurred. (XX000: Unknown prepared statement with name: )
 ---> Npgsql.PostgresException (0x80004005): XX000: Unknown prepared statement with name: 
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSourceCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataSourceCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
  Exception data:
    Severity: ERROR
    SqlState: XX000
    MessageText: Unknown prepared statement with name: 
   --- End of inner exception stack trace ---
```

**Comment by Seddryck** [comment]
I didn't try to create tables with npgsql on GlareDB
