### ISSUE TITLE
Panic when trying to connect to Clickhouse TLS port without secure flag

### ISSUE THREAD

**Issue by vrongmeal** [GlareDB/glaredb#2360]
## Description

> We currently return an error early assuming they are trying to connect to TLS port based on the default port number.

`9440` is the default TLS port.

```
> create external database ch from clickhouse options (connection_string = 'clickhouse://default:<pwd>@gfvi4aovgg.us-east1.gcp.clickhouse.cloud:9440’ );

thread 'main' panicked at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/lib.rs:325:41:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/option.rs:931:21
   4: clickhouse_rs::ClientHandle::hello::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/lib.rs:325:36
   5: clickhouse_rs::Client::open::{{closure}}::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/lib.rs:293:32
   6: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/time/timeout.rs:202:33
   7: clickhouse_rs::with_timeout::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/lib.rs:588:43
   8: clickhouse_rs::Client::open::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/lib.rs:298:10
   9: clickhouse_rs::pool::Pool::new_connection::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/pool/mod.rs:211:58
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/future/future.rs:125:9
  11: futures_util::future::future::FutureExt::poll_unpin
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
  12: clickhouse_rs::pool::Pool::handle_futures
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/pool/mod.rs:216:19
  13: clickhouse_rs::pool::Pool::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/pool/mod.rs:184:9
  14: <clickhouse_rs::pool::futures::get_handle::GetHandle as core::future::future::Future>::poll
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clickhouse-rs-1.1.0-alpha.1/src/pool/futures/get_handle.rs:28:9
  15: datasources::clickhouse::ClickhouseAccessState::connect::{{closure}}
             at ./crates/datasources/src/clickhouse/mod.rs:114:44
  16: datasources::clickhouse::ClickhouseAccess::validate_access::{{closure}}
             at ./crates/datasources/src/clickhouse/mod.rs:51:72
  17: sqlexec::planner::session_planner::SessionPlanner::plan_create_external_database::{{closure}}
             at ./crates/sqlexec/src/planner/session_planner.rs:316:42
  18: sqlexec::planner::session_planner::SessionPlanner::plan_ast::{{closure}}
             at ./crates/sqlexec/src/planner/session_planner.rs:142:58
  19: sqlexec::context::local::PreparedStatement::build::{{closure}}
             at ./crates/sqlexec/src/context/local.rs:411:56
  20: sqlexec::context::local::LocalSessionContext::prepare_statement::{{closure}}
             at ./crates/sqlexec/src/context/local.rs:246:57
  21: sqlexec::session::Session::prepare_statement::{{closure}}
             at ./crates/sqlexec/src/session.rs:510:61
  22: glaredb::local::LocalSession::execute::{{closure}}
             at ./crates/glaredb/src/local.rs:198:18
  23: glaredb::local::LocalSession::run_interactive::{{closure}}
             at ./crates/glaredb/src/local.rs:159:53
  24: glaredb::local::LocalSession::run::{{closure}}
             at ./crates/glaredb/src/local.rs:115:36
  25: <glaredb::args::local::LocalArgs as glaredb::commands::RunCommand>::run::{{closure}}
             at ./crates/glaredb/src/commands.rs:124:30
  26: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:63
  27: tokio::runtime::coop::with_budget
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:107:5
  28: tokio::runtime::coop::budget
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:73:5
  29: tokio::runtime::park::CachedParkThread::block_on
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:31
  30: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/blocking.rs:66:9
  31: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  32: tokio::runtime::context::runtime::enter_runtime
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/runtime.rs:65:16
  33: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  34: tokio::runtime::runtime::Runtime::block_on
             at /Users/sean/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/runtime.rs:350:45
  35: <glaredb::args::local::LocalArgs as glaredb::commands::RunCommand>::run
             at ./crates/glaredb/src/commands.rs:71:9
  36: glaredb::commands::Commands::run
             at ./crates/glaredb/src/commands.rs:40:39
  37: glaredb::main
             at ./crates/glaredb/src/bin/main.rs:76:5
  38: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by scsmithr** [comment]
Don't think this is relevant anymore with the switch to klickhouse
