### ISSUE TITLE
CLI tests don't work for me

### ISSUE THREAD

**Issue by scsmithr** [GlareDB/glaredb#2467]
## Description

Related: https://github.com/GlareDB/glaredb/issues/2444

```
test test_storage_config_require_location ... FAILED
test test_query_or_file ... FAILED
test test_data_dir ... FAILED
test test_parse_storage_options_ok ... FAILED
test test_parse_storage_options_not_ok ... FAILED

failures:

---- test_storage_config_require_location stdout ----
thread 'test_storage_config_require_location' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected stderr, failed (var.contains(error: the following required arguments were not provided:) && var.contains(--location <LOCATION>))
├── var as str: 
└── var.contains(error: the following required arguments were not provided:)
    └── var: 

command=`"/Users/sean/Code/github.com/glaredb/glaredb/target/debug/glaredb" "-o" "foo=bar"`
code=<interrupted>
stdout=""
stderr=""


---- test_query_or_file stdout ----
thread 'test_query_or_file' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected stderr, failed var.contains(the argument '--query <QUERY>' cannot be used with '[FILE]')
├── var: 
└── var as str: 

command=`"/Users/sean/Code/github.com/glaredb/glaredb/target/debug/glaredb" "-q" "SELECT * FROM foo" "foo.sql"`
code=<interrupted>
stdout=""
stderr=""


---- test_data_dir stdout ----
thread 'test_data_dir' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=<interrupted>
stderr=```""```
command=`"/Users/sean/Code/github.com/glaredb/glaredb/target/debug/glaredb" "-f" "/var/folders/4l/fnrk81pn6nj924xq52rwxnbc0000gn/T/.tmplukmlJ" "-q" "create table test as select 1"`
code=<interrupted>
stdout=""
stderr=""


---- test_parse_storage_options_ok stdout ----
thread 'test_parse_storage_options_ok' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=<interrupted>
stderr=```""```
command=`"/Users/sean/Code/github.com/glaredb/glaredb/target/debug/glaredb" "-l" "/var/folders/4l/fnrk81pn6nj924xq52rwxnbc0000gn/T/.tmpPg1fk0" "-o" "foo=bar" "-q" "select 1"`
code=<interrupted>
stdout=""
stderr=""

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_parse_storage_options_not_ok stdout ----
thread 'test_parse_storage_options_not_ok' panicked at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5:
Unexpected stderr, failed var.contains(Expected key-value pair delimited by an equals sign, got)
├── var: 
└── var as str: 

command=`"/Users/sean/Code/github.com/glaredb/glaredb/target/debug/glaredb" "-l" "foo" "-o" "foobar"`
code=<interrupted>
stdout=""
stderr=""



failures:
    test_data_dir
    test_parse_storage_options_not_ok
    test_parse_storage_options_ok
    test_query_or_file
    test_storage_config_require_location

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.50s

error: test failed, to rerun pass `-p glaredb --test local_args_test`
error: Recipe `test` failed on line 54 with exit code 101
error: Recipe `unit-tests` failed on line 58 with exit code 101
```

Running `just unit-tests` in a bog standard zsh shell on macos.

**Comment by tychoish** [comment]
@scsmithr safe to close?

**Comment by scsmithr** [comment]
I think so, removing the timeouts fixed this for me. I think longer term we'll need to figure out a better way of running these tests as to not rely on timeouts (we still have some for the server tests).
