### ISSUE TITLE
native table issues with `FixedSizeList` + case sensitive column names. 

### ISSUE THREAD

**Issue by universalmind303** [GlareDB/glaredb#2777]
## Description

a simple table with two fields `"Text"`, and `embeddings`

```sql
> select * from lance_scan('./embeddings');
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────┐
│ embeddings                                                                                              │ Text │
│ ──                                                                                                      │ ──   │
│ FixedSizeList<Float32; 1536>                                                                            │ Utf8 │
╞═════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════╡
│ [0.019264393, -0.06450473, -0.0016729431, 0.07811243, 0.021637829, -0.015546009, -0.015044951, 0.04578… │ Hel… │
│ [-0.008556553, -0.028633503, 0.008491013, 0.11569916, -0.036906052, -0.027395533, 0.010631972, 0.03783… │ Wor… │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────┘
```

I can query the table fine, and even save it as a "native" table

```sql
create table delta as select * from lance_scan('./embeddings');
Table created
```

but if i try to select from it, i get a panic

```sql
> select * from delta;
thread 'main' panicked at crates/datasources/src/native/access.rs:458:87:
called `Result::unwrap()` on an `Err` value: SchemaError(FieldNotFound { field: Column { relation: None, name: "text" }, valid_fields: [Column { relation: None, name: "embeddings" }, Column { relation: None, name: "Text" }] }, Some(""))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It looks like the 'embeddings' field is dropped somewhere? 

```sql
> select * from list_columns(default, public, delta);
┌─────────────┬───────────┬──────────┐
│ column_name │ data_type │ nullable │
│ ──          │ ──        │ ──       │
│ Utf8        │ Utf8      │ Boolean  │
╞═════════════╪═══════════╪══════════╡
│ Text        │ Utf8      │ true     │
└─────────────┴───────────┴──────────┘
```

```sql
> select embeddings from delta;
Error: Schema error: No field named embeddings. Valid fields are delta."Text".
```

**Comment by tychoish** [comment]
How does this relate to your previous changes to the metadata on the tables to address the handling of types like these? Is this a regression or was that fix incomplete?

**Comment by universalmind303** [comment]
This is an edge case when one of the fields is case sensitive. 

the old one https://github.com/GlareDB/glaredb/issues/2547 was closed via https://github.com/GlareDB/glaredb/pull/2607/, but case sensitive fields were not tested. if we go through that flow again, but make a field case sensitive, it results in an error.

```sql
> create table test as select vector, point as "Point" from lance_scan('./testdata/lance/table1');
> select * from test;
thread 'main' panicked at crates/datasources/src/native/access.rs:458:87:
called `Result::unwrap()` on an `Err` value: SchemaError(FieldNotFound { field: Column { relation: None, name: "point" }, valid_fields: [Column { relation: None, name: "vector" }, Column { relation: None, name: "Point" }] }, Some(""))
```
